# Generated by Django 6.0.6 on 2026-06-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zgloszenia', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=150)),
                ('temat', models.CharField(max_length=200)),
                ('opis_problemu', models.TextField()),
                ('modul', models.CharField(choices=[('offer_mng', 'Zarządzanie ofertą'), ('offer', 'Oferta publiczna'), ('auth', 'Logowanie/Rejestracja'), ('other', 'Inne')], max_length=50)),
                ('zalacznik', models.ImageField(blank=True, null=True, upload_to='issues_attachments/')),
            ],
        ),
    ]
