# Generated by Django 6.0.6 on 2026-06-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publikuj', models.BooleanField(default=True)),
                ('kolejnosc', models.IntegerField(default=0)),
                ('nazwa', models.CharField(max_length=150)),
                ('tytul', models.CharField(max_length=150)),
                ('opis', models.TextField(blank=True)),
                ('kategoria_nadrzedna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Szkolenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publikuj', models.BooleanField(default=True)),
                ('kolejnosc', models.IntegerField(default=0)),
                ('liczba_godzin', models.IntegerField()),
                ('numer', models.CharField(max_length=50)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szkolenia', to='offer.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zgoda_rodo', models.BooleanField(default=False)),
                ('status', models.CharField(default='Oczekująca', max_length=50)),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('szkolenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.szkolenie')),
            ],
        ),
    ]
